### PR TITLE
Utilize nsec info in timestamp whenever available

### LINKED ISSUE #19: subsecond info is not sent to NewRelic API
Hi, 

I found that all the log entries sent to NewRelic Logs lost their subsecond info in the timestamp. So all the timestamps in the Logs dashboard only have integer second numbers.

After a bit of digging, I found out that the `nsec` field in the timestamp is not utilized when forming the request data to NR API. I have a commit that works for me https://github.com/danielsig727/newrelic-fluentd-output/commit/48602db2c6b9472159418e9a683a1281eef61768 . If you're fine with it, I can create a PR for it. Thanks

### PR DESCRIPTION
**Pull request by danielsig727**
closes #19 

The most general way I found to detect if the nsec info is available is using `defined? timestamp.nsec`, since sometimes `timestamp` is an integer, sometimes an object (maybe depending on the upstream plugins). Feel free to suggest if there are better ways to implement it. :)

### CODE REVIEW

**Comment by danielsig727** [comment]
@bmcfeely could you help take a look? thank you!

**Comment by bmcfeely** [comment]
@danielsig727 My apologies! On it right now...

**Comment by bmcfeely** [comment]
@danielsig727 I tested this locally and it looks good. Nice work!
Since this took me forever to get to, can you bump the version number again to `1.1.8` and I'll merge? Thank you!

**Comment by danielsig727** [comment]
@bmcfeely done. thanks :)

**Pull request merged**
